name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_PREVIEW_DEPLOY: ${{ secrets.VERCEL_PREVIEW_DEPLOY }}

on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        if: env.VERCEL_PREVIEW_DEPLOY == 'true'
        run: npm install --global vercel
      - name: Pull Vercel Environment Information
        if: env.VERCEL_PREVIEW_DEPLOY == 'true'
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        if: env.VERCEL_PREVIEW_DEPLOY == 'true'
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        if: env.VERCEL_PREVIEW_DEPLOY == 'true'
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
